export const fullAssetList = [
    "BTCUSDT", "ETHUSDT", "SOLUSDT", "BNBUSDT", "XRPUSDT", "DOGEUSDT", "ADAUSDT", "SHIBUSDT", "AVAXUSDT", "DOTUSDT",
    "MATICUSDT", "LINKUSDT", "TRXUSDT", "LTCUSDT", "BCHUSDT", "NEARUSDT", "UNIUSDT", "ATOMUSDT", "ETCUSDT", "FILUSDT",
    "PEPEUSDT", "WIFUSDT", "NOTUSDT", "TONUSDT", "ORDIUSDT", "WLDUSDT", "ARBUSDT", "APTUSDT", "SUIUSDT", "OPUSDT",
    "INJUSDT", "ARUSDT", "RUNEUSDT", "FTMUSDT", "AAVEUSDT", "GRTUSDT", "MKRUSDT", "SNXUSDT", "LDOUSDT", "SANDUSDT",
    "MANAUSDT", "AXSUSDT", "GALAUSDT", "THETAUSDT", "XTZUSDT", "EOSUSDT", "KSMUSDT", "ZECUSDT", "DASHUSDT", "COMPUSDT",
    "CRVUSDT", "1INCHUSDT", "DYDXUSDT", "GMXUSDT", "SUSHIUSDT", "YFIUSDT", "IMXUSDT", "BLURUSDT", "CELOUSDT", "FLOKIUSDT",
    "MEMEUSDT", "ENAUSDT", "WUSDT", "JUPUSDT", "JTOUSDT", "PYTHUSDT", "BOMEUSDT", "ICPUSDT", "VETUSDT", "XLMUSDT",
    "HBARUSDT", "ALGOUSDT", "EGLDUSDT", "FLOWUSDT", "CHZUSDT", "MINAUSDT"
];

// A curated list of top assets for simpler dropdowns.
export const topAssetList = [
    "BTCUSDT", "ETHUSDT", "BNBUSDT", "SOLUSDT", "XRPUSDT", "DOGEUSDT", "ADAUSDT", "AVAXUSDT", "DOTUSDT",
    "LINKUSDT", "MATICUSDT", "LTCUSDT", "NEARUSDT", "UNIUSDT", "ATOMUSDT", "ETCUSDT", "FILUSDT", "APTUSDT", "SUIUSDT", "OPUSDT",
    "PEPEUSDT", "WIFUSDT", "TONUSDT", "ORDIUSDT", "WLDUSDT"
];
