
export const strategyIndicatorMap: Record<string, string[]> = {
  'awesome-oscillator': ['Awesome Oscillator'],
  'bollinger-bands': ['Bollinger Bands'],
  'cci-reversion': ['CCI'],
  'chaikin-money-flow': ['Chaikin Money Flow'],
  'coppock-curve': ['Coppock Curve', 'WMA', 'RoC'],
  'donchian-channels': ['Donchian Channels'],
  'elder-ray-index': ['Elder-Ray Index', 'EMA'],
  'ema-crossover': ['EMA'],
  'heikin-ashi-trend': ['Heikin-Ashi'],
  'ichimoku-cloud': ['Ichimoku Cloud'],
  'keltner-channels': ['Keltner Channels', 'ATR'],
  'macd-crossover': ['MACD', 'EMA'],
  'momentum-cross': ['Momentum'],
  'obv-divergence': ['OBV', 'SMA'],
  'parabolic-sar-flip': ['Parabolic SAR'],
  'peak-formation-fib': ['EMA', 'Fibonacci Retracement'],
  'hyper-peak-formation': ['EMA', 'Fibonacci Retracement'],
  'liquidity-order-flow': ['EMA', 'FVG'],
  'liquidity-grab': ['Swing Points'],
  'ema-cci-macd': ['EMA', 'CCI', 'MACD'],
  'smoothed-heikin-ashi-pullback': ['Heikin-Ashi', 'Candlestick Patterns'],
  'pivot-point-reversal': ['Pivot Points'],
  'reverse-pff': ['EMA', 'Fibonacci Retracement'],
  'rsi-divergence': ['RSI'],
  'sma-crossover': ['SMA'],
  'stochastic-crossover': ['Stochastic Oscillator'],
  'supertrend': ['Supertrend', 'ATR'],
  'volume-delta': ['Volume Profile (POC)', 'Volume Delta'],
  'vwap-cross': ['VWAP'],
  'williams-r': ['Williams %R'],
  'code-based-consensus': ['Multiple Indicators', 'Ensemble'],
  'mtf-engulfing': ['EMA', 'ATR', 'Engulfing Pattern'],
};
